config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  resources :users
  get "/register", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  namespace :admin do
    get "/", to: "application#home"
    resources :users, :tours
  end

  resources :categorys, only: %i(index show) do
    resources :tours, only: %i(index show)  do
      resources :tour_details, only: %i(index show)
    end
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  belongs_to :category, optional: true
  has_many :books, dependent: :destroy
  has_many :tags, as: :tag_type, dependent: :destroy
  has_many :tour_details, dependent: :destroy
  has_many :reviews, as: :review_type, dependent: :destroy
  has_many :images, as: :image_type, dependent: :destroy

  # Ex:- scope :active, -> {where(:active => true)}
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < Admin::ApplicationController
  before_action :load_tour, except: %i(new create index)
  def index
    @tours = Tour.paginate page: params[:page]
  end

  def show; end

  def new
    @tour = Tour.new
  end

  def create
    @tour = Tour.new params[:tour]
    if @tour.save
      flash[:success] = "Tour create scuccess !"
      redirect_to @tour
    else
      flash[:danger] = "Tour incorrect !"
      render :new
    end
  end

  def edit; end

  def update
    if @tour.update params[:tour]
      flash[:success] = " Tour update success !"
      redirect_to @tour
    else
      render :edit
    end
  end

  def destroy
    if @tour.destroy
      flash[:success] = " Tour has deleted !"
    else
      flash[:danger] = "Tour don't exist !"
    end
    redirect_to admin_tours_path
  end

  private
  def load_tour
    @tour = Tour.find_by id: params[:id]
    return if @tour

    flash[:danger] = "Tour don't exist !"
    redirect_to admin_tours_path
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :load_tour, only: %i(index show)
  def index; end

  def show
    @tour_details = @tour.tour_details
  end

  private
  def load_tour
    @tour = Tour.find_by id: params[:id]
    return if @tour

    flash[:danger] = "Tours don't exist !"
    redirect_to root_path
  end
end

app/helpers/admin/tours_helper.rb
module Admin::ToursHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/admin/tours/index.html.erb
<% provide :title, "Manager Tour " %>
<div class="row">
  <div class="col-lg">
    <h2 class="title-1 m-b-25">Tour Manager</h2>
    <div class="table-responsive table--no-card m-b-40">
      <div class="just-item-center text-center">
        <%= will_paginate %>
      </div>
      <table class="table table-borderless table-striped table-earning">
        <thead>
          <tr>
            <th>Title</th>
            <th>City</th>
            <th class="text-right">Price</th>
            <th class="text-right">Area</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @tours.each do |tour| %>
          <tr>
            <td><%= tour.title %></td>
            <td><%= tour.category.city %></td>
            <td class="text-right"><%= tour.price %> $</td>
            <td class="text-right"><%= tour.category.area %></td>
            <td>
              <div class="table-data-feature">
                <%= link_to  tour do %>
                <button class="item" data-toggle="tooltip" data-placement="top" title="Details">
                  <i class="zmdi zmdi-assignment"></i>
                </button>
                <% end %>
                <%= link_to edit_admin_tour_path(tour) do %>
                <button class="item" data-toggle="tooltip" data-placement="top" title="Edit">
                  <i class="zmdi zmdi-edit"></i>
                </button>
                <% end %>
                <%= link_to admin_tour_path(tour), method: :delete, data: {confirm: " Are You Sure !" } do %>
                <button class="item" data-toggle="tooltip" data-placement="top" title="Delete">
                  <i class="zmdi zmdi-delete"></i>
                </button>
                <% end %>
              </div>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="just-item-center text-center">
        <%= will_paginate %>
      </div>
    </div>
  </div>
</div>