config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  resources :users
  get "/register", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  namespace :admin do
    get "/", to: "application#home"
    resources :users, :tours
  end

  resources :categorys, only: %i(index show) do
    resources :tours, only: %i(index show)  do
      resources :tour_details, only: %i(index show)
    end
  end
end

app/views/shared/_category.html.erb
<div class="popular_destination_area">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <div class="section_title text-center mb_70">
          <h3>Popular Destination</h3>
          <p>Suffered alteration in some form, by injected humour or good day randomised booth anim 8-bit
            hella wolf moon beard words.</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 col-md-6">
        <div class="single_destination">
          <div class="thumb">
            <%= image_tag("destination/1.png", :alt=>"") %>
          </div>
          <div class="content">
            <p class="d-flex align-items-center">Italy <a href="travel_destination.html"> 07 Places</a>
            </p>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="single_destination">
          <div class="thumb">
            <%= image_tag("destination/2.png", :alt=>"") %>
          </div>
          <div class="content">
            <p class="d-flex align-items-center">Brazil <a href="travel_destination.html"> 03 Places</a>
            </p>

          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="single_destination">
          <div class="thumb">
            <%= image_tag("destination/3.png", :alt=>"") %>
          </div>
          <div class="content">
            <p class="d-flex align-items-center">America <a href="travel_destination.html"> 10
                Places</a> </p>

          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="single_destination">
          <div class="thumb">
            <%= image_tag("destination/4.png", :alt=>"") %>
          </div>
          <div class="content">
            <p class="d-flex align-items-center">Nepal <a href="travel_destination.html"> 02 Places</a>
            </p>

          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="single_destination">
          <div class="thumb">
            <%= image_tag("destination/5.png", :alt=>"") %>
          </div>
          <div class="content">
            <p class="d-flex align-items-center">Maldives <a href="travel_destination.html"> 02
                Places</a> </p>

          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="single_destination">
          <div class="thumb">
            <%= image_tag("destination/6.png", :alt=>"") %>
          </div>
          <div class="content">
            <p class="d-flex align-items-center">Indonesia <a href="travel_destination.html"> 05
                Places</a> </p>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_categorys.html.erb
<div class="popular_destination_area">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <div class="section_title text-center mb_70">
          <h3>Popular Destination</h3>
          <p>Suffered alteration in some form, by injected humour or good day randomised booth anim 8-bit
            hella wolf moon beard words.</p>
        </div>
      </div>
    </div>
    <div class="row">
      <% @categorys.each do |category| %>
      <div class="col-lg-4 col-md-6">
        <div class="single_destination">
          <div class="thumb">
            <%= image_tag("destination/2.png", :alt=>"") %>
          </div>
          <div class="content">
            <p class="d-flex align-items-center"><%= category.city %> <a href="travel_destination.html"><%= category.tours.count %> plances</a>
            </p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_city.html.erb
<div class="popular_places_area">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <div class="section_title text-center mb_70">
          <h3>Popular Places</h3>
          <p>Suffered alteration in some form, by injected humour or good day randomised booth anim 8-bit
            hella wolf moon beard words.</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 col-md-6">
        <div class="single_place">
          <div class="thumb">
            <%= image_tag("place/1.png", :alt=>"") %>
            <a href="#" class="prise">$500</a>
          </div>
          <div class="place_info">
            <a href="destination_details.html">
              <h3>California</h3>
            </a>
            <p>United State of America</p>
            <div class="rating_days d-flex justify-content-between">
              <span class="d-flex justify-content-center align-items-center">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <a href="#">(20 Review)</a>
              </span>
              <div class="days">
                <i class="fa fa-clock-o"></i>
                <a href="#">5 Days</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="single_place">
          <div class="thumb">
            <%= image_tag("place/2.png", :alt=>"") %>
            <a href="#" class="prise">$500</a>
          </div>
          <div class="place_info">
            <a href="destination_details.html">
              <h3>Korola Megna</h3>
            </a>
            <p>United State of America</p>
            <div class="rating_days d-flex justify-content-between">
              <span class="d-flex justify-content-center align-items-center">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <a href="#">(20 Review)</a>
              </span>
              <div class="days">
                <i class="fa fa-clock-o"></i>
                <a href="#">5 Days</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="single_place">
          <div class="thumb">
            <%= image_tag("place/3.png", :alt=>"") %>
            <a href="#" class="prise">$500</a>
          </div>
          <div class="place_info">
            <a href="destination_details.html">
              <h3>London</h3>
            </a>
            <p>United State of America</p>
            <div class="rating_days d-flex justify-content-between">
              <span class="d-flex justify-content-center align-items-center">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <a href="#">(20 Review)</a>
              </span>
              <div class="days">
                <i class="fa fa-clock-o"></i>
                <a href="#">5 Days</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="single_place">
          <div class="thumb">
            <%= image_tag("place/4.png", :alt=>"") %>
            <a href="#" class="prise">$500</a>
          </div>
          <div class="place_info">
            <a href="destination_details.html">
              <h3>Miami Beach</h3>
            </a>
            <p>United State of America</p>
            <div class="rating_days d-flex justify-content-between">
              <span class="d-flex justify-content-center align-items-center">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <a href="#">(20 Review)</a>
              </span>
              <div class="days">
                <i class="fa fa-clock-o"></i>
                <a href="#">5 Days</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="single_place">
          <div class="thumb">
            <%= image_tag("place/5.png", :alt=>"") %>
            <a href="#" class="prise">$500</a>
          </div>
          <div class="place_info">
            <a href="destination_details.html">
              <h3>California</h3>
            </a>
            <p>United State of America</p>
            <div class="rating_days d-flex justify-content-between">
              <span class="d-flex justify-content-center align-items-center">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <a href="#">(20 Review)</a>
              </span>
              <div class="days">
                <i class="fa fa-clock-o"></i>
                <a href="#">5 Days</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="single_place">
          <div class="thumb">
            <%= image_tag("place/6.png", :alt=>"") %>
            <a href="#" class="prise">$500</a>
          </div>
          <div class="place_info">
            <a href="destination_details.html">
              <h3>Saintmartine Iceland</h3>
            </a>
            <p>United State of America</p>
            <div class="rating_days d-flex justify-content-between">
              <span class="d-flex justify-content-center align-items-center">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <a href="#">(20 Review)</a>
              </span>
              <div class="days">
                <i class="fa fa-clock-o"></i>
                <a href="#">5 Days</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="more_place_btn text-center">
          <a class="boxed-btn4" href="#">More Places</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul class="type_error">
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer_top">
    <div class="container">
      <div class="row">
        <div class="col-xl-4 col-md-6 col-lg-4 ">
          <div class="footer_widget">
            <div class="footer_logo">
              <a href="#">
                <%= image_tag("footer_logo.png", :alt=>"")%>
              </a>
            </div>
            <p>5th flora, 700/D kings road, green <br> lane New York-1782 <br>
              <a href="#">+10 367 826 2567</a> <br>
              <a href="#">contact@carpenter.com</a>
            </p>
            <div class="socail_links">
              <ul>
                <li>
                  <a href="#">
                    <i class="ti-facebook"></i>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="ti-twitter-alt"></i>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-instagram"></i>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-pinterest"></i>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-youtube-play"></i>
                  </a>
                </li>
              </ul>
            </div>

          </div>
        </div>
        <div class="col-xl-2 col-md-6 col-lg-2">
          <div class="footer_widget">
            <h3 class="footer_title">
              Company
            </h3>
            <ul class="links">
              <li><a href="#">Pricing</a></li>
              <li><a href="#">About</a></li>
              <li><a href="#"> Gallery</a></li>
              <li><a href="#"> Contact</a></li>
            </ul>
          </div>
        </div>
        <div class="col-xl-3 col-md-6 col-lg-3">
          <div class="footer_widget">
            <h3 class="footer_title">
              Popular destination
            </h3>
            <ul class="links double_links">
              <li><a href="#">Indonesia</a></li>
              <li><a href="#">America</a></li>
              <li><a href="#">India</a></li>
              <li><a href="#">Switzerland</a></li>
              <li><a href="#">Italy</a></li>
              <li><a href="#">Canada</a></li>
              <li><a href="#">Franch</a></li>
              <li><a href="#">England</a></li>
            </ul>
          </div>
        </div>
        <div class="col-xl-3 col-md-6 col-lg-3">
          <div class="footer_widget">
            <h3 class="footer_title">
              Instagram
            </h3>
            <div class="instagram_feed">
              <div class="single_insta">
                <a href="#">
                  <%= image_tag("instagram/1.png",:alt =>"") %>
                </a>
              </div>
              <div class="single_insta">
                <a href="#">
                  <%= image_tag("instagram/2.png", :alt=>"")%>
                </a>
              </div>
              <div class="single_insta">
                <a href="#">
                  <%= image_tag("instagram/3.png", :alt=>"")%>
                </a>
              </div>
              <div class="single_insta">
                <a href="#">
                  <%= image_tag("instagram/4.png", :alt=>"")%>
                </a>
              </div>
              <div class="single_insta">
                <a href="#">
                  <%= image_tag("instagram/5.png", :alt=>"")%>
                </a>
              </div>
              <div class="single_insta">
                <a href="#">
                  <%= image_tag("instagram/6.png", :alt=>"")%>

                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="copy-right_text">
    <div class="container">
      <div class="footer_border"></div>
      <div class="row">
        <div class="col-xl-12">
          <p class="copy_right text-center">
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;
            <script>
              document.write(new Date().getFullYear());
            </script> All rights reserved | This
            template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
    <header>
      <div class="header-area ">
        <div id="sticky-header" class="main-header-area">
          <div class="container-fluid">
            <div class="header_bottom_border">
              <div class="row align-items-center">
                <div class="col-xl-2 col-lg-2">
                  <div class="logo">
                    <%= link_to  image_tag("logo.png"), root_path%>
                  </div>
                </div>
                <div class="col-xl-6 col-lg-6">
                  <div class="main-menu  d-none d-lg-block">
                    <nav>
                      <ul id="navigation">
                        <% if current_user&.supervisor? %>
                        <li><%= link_to "Admin Page", admin_path %></li>
                        <% end %>
                        <li><%= link_to "Home", root_path, class:"active" %></li>
                        <li><%= link_to  "About",about_path %></li>
                        <li><%= link_to  "Destination", root_path %></li>
                        <li><%= link_to  "Blog", root_path %></li>
                        <li><%= link_to  "Contact", contact_path %></li>
                      </ul>
                    </nav>
                  </div>
                </div>
                <div class="col-xl-4 col-lg-4 d-none d-lg-block">
                  <div class="social_wrap d-flex align-items-center justify-content-end">
                    <% if logged_in? %>
                    <div class="main-menu avatar-nav">
                      <ul id="navigation">
                        <li><%= link_to @current_user do %>
                          <%= image_tag("avatar/3.png", :alt=>"",:class => "avatar")%>
                          <%= @current_user.name %>
                          <i class="ti-angle-down"></i>
                          <% end %>
                          <ul class="submenu">
                            <li><a href="#"><i class="fa fa-user-o"></i> Profile</a></li>
                            <li><a href="#"><i class="fa fa-calendar-o"></i> Calendar</a></li>
                            <li><a href="#"><i class="fa fa-sliders"></i> Settings</a></li>
                            <li>
                              <div class="dropdown-divider"></div>
                            </li>
                            <li><%= link_to " Logout", logout_path,  method: :delete %></li>
                          </ul>
                        </li>
                      </ul>
                    </div>
                  </div>
                  <% else %>
                  <div class="number">
                    <p> <i class="fa fa-phone"></i> 10(256)-928 256</p>
                  </div>
                  <div class="number">
                    <%= link_to  "Log In", login_path ,class:"btn btn-outline-info btn-md btn-rounded btn-navbar waves-effect waves-light"%>
                  </div>
                  <div class="social_links d-none d-xl-block">
                    <ul>
                      <li><a href="#"> <i class="fa fa-instagram"></i> </a></li>
                      <li><a href="#"> <i class="fa fa-linkedin"></i> </a></li>
                      <li><a href="#"> <i class="fa fa-facebook"></i> </a></li>
                      <li><a href="#"> <i class="fa fa-google-plus"></i> </a></li>
                    </ul>
                  </div>
                  <% end %>
                </div>
              </div>
              <div class="seach_icon">
                <a data-toggle="modal" data-target="#exampleModalCenter" href="#">
                  <i class="fa fa-search"></i>
                </a>
              </div>
              <div class="col-12">
                <div class="mobile_menu d-block d-lg-none"></div>
              </div>
            </div>
          </div>

        </div>
      </div>
      </div>
    </header>

app/views/shared/_review.html.erb
 <div class="testimonial_area">
   <div class="container">
     <div class="row">
       <div class="col-xl-12">
         <div class="testmonial_active owl-carousel">
           <div class="single_carousel">
             <div class="row justify-content-center">
               <div class="col-lg-8">
                 <div class="single_testmonial text-center">
                   <div class="author_thumb">
                     <%= image_tag("testmonial/author.png", :alt=>"") %>
                   </div>
                   <p>"Working in conjunction with humanitarian aid agencies, we have supported
                     programmes to help alleviate human suffering.</p>
                   <div class="testmonial_author">
                     <h3>- Micky Mouse</h3>
                   </div>
                 </div>
               </div>
             </div>
           </div>
           <div class="single_carousel">
             <div class="row justify-content-center">
               <div class="col-lg-8">
                 <div class="single_testmonial text-center">
                   <div class="author_thumb">
                     <%= image_tag("testmonial/author.png", :alt=>"") %>
                   </div>
                   <p>"Working in conjunction with humanitarian aid agencies, we have supported
                     programmes to help alleviate human suffering.</p>
                   <div class="testmonial_author">
                     <h3>- Tom Mouse</h3>
                   </div>
                 </div>
               </div>
             </div>
           </div>
           <div class="single_carousel">
             <div class="row justify-content-center">
               <div class="col-lg-8">
                 <div class="single_testmonial text-center">
                   <div class="author_thumb">
                     <%= image_tag("testmonial/author.png", :alt=>"") %>
                   </div>
                   <p>"Working in conjunction with humanitarian aid agencies, we have supported
                     programmes to help alleviate human suffering.</p>
                   <div class="testmonial_author">
                     <h3>- Jerry Mouse</h3>
                   </div>
                 </div>
               </div>
             </div>
           </div>
         </div>
       </div>
     </div>
   </div>
 </div>

app/views/shared/_search-form.html.erb
  <div class="modal fade custom_search_pop" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="serch_form">
          <input type="text" placeholder="Search">
          <button type="submit">search</button>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_service.html.erb
<div class="travel_variation_area">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-6">
        <div class="single_travel text-center">
          <div class="icon">
            <%= image_tag("svg_icon/1.svg", :alt=>"") %>
          </div>
          <h3>Comfortable Journey</h3>
          <p>A wonderful serenity has taken to the possession of my entire soul.</p>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="single_travel text-center">
          <div class="icon">
            <%= image_tag("svg_icon/2.svg", :alt=>"") %>
          </div>
          <h3>Luxuries Hotel</h3>
          <p>A wonderful serenity has taken to the possession of my entire soul.</p>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="single_travel text-center">
          <div class="icon">
            <%= image_tag("svg_icon/3.svg", :alt=>"") %>
          </div>
          <h3>Travel Guide</h3>
          <p>A wonderful serenity has taken to the possession of my entire soul.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_slide.html.erb
<div class="bradcam_area <%= yield(:image_slide)%>">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="bradcam_text text-center">
          <h3><%= yield(:title_slide) %></h3>
          <p><%= yield(:content_slide) %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_subscribe.html.erb
<div class="newletter_area overlay">
  <div class="container">
    <div class="row justify-content-center align-items-center">
      <div class="col-lg-10">
        <div class="row align-items-center">
          <div class="col-lg-5">
            <div class="newsletter_text">
              <h4>Subscribe Our Newsletter</h4>
              <p>Subscribe newsletter to get offers and about
                new places to discover.</p>
            </div>
          </div>
          <div class="col-lg-7">
            <div class="mail_form">
              <div class="row no-gutters">
                <div class="col-lg-9 col-md-8">
                  <div class="newsletter_field">
                    <input type="email" placeholder="Your mail">
                  </div>
                </div>
                <div class="col-lg-3 col-md-4">
                  <div class="newsletter_btn">
                    <button class="boxed-btn4 " type="submit">Subscribe</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_tour.html.erb
<div class="popular_places_area">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <div class="section_title text-center mb_70">
          <h3>Popular Places</h3>
          <p>Suffered alteration in some form, by injected humour or good day randomised booth anim 8-bit
            hella wolf moon beard words.</p>
        </div>
      </div>
    </div>
    <div class="row">
      <% @tours.each do |tour| %>
      <div class="col-lg-4 col-md-6">
        <div class="single_place">
          <div class="thumb">
            <%= image_tag("place/1.png", :alt=>"") %>
            <a href="#" class="prise"><%= tour.tour_details.count %> places</a>
          </div>
          <div class="place_info">
            <a href="destination_details.html">
              <h3><%= tour.category.city %></h3>
              <span>
                <h4>$ <%= tour.price %><h4>
              </span>
            </a>
            <div class="rating_days d-flex justify-content-between">
              <span class="d-flex justify-content-center align-items-center">
                <% tour.rate.times do %>
                <i class="fa fa-star"></i>
                <% end %>
              </span>
              <div class="days">
                <i class="fa fa-clock-o"></i>
                <a href="#">5 Days</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="more_place_btn text-center">
          <a class="boxed-btn4" href="#">More Places</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_trip.html.erb
 <div class="recent_trip_area">
   <div class="container">
     <div class="row justify-content-center">
       <div class="col-lg-6">
         <div class="section_title text-center mb_70">
           <h3>Recent Trips</h3>
         </div>
       </div>
     </div>
     <div class="row">
       <div class="col-lg-4 col-md-6">
         <div class="single_trip">
           <div class="thumb">
             <%= image_tag("trip/1.png", :alt=>"") %>
           </div>
           <div class="info">
             <div class="date">
               <span>Oct 12, 2019</span>
             </div>
             <a href="#">
               <h3>Journeys Are Best Measured In
                 New Friends</h3>
             </a>
           </div>
         </div>
       </div>
       <div class="col-lg-4 col-md-6">
         <div class="single_trip">
           <div class="thumb">
             <%= image_tag("trip/2.png", :alt=>"") %>
           </div>
           <div class="info">
             <div class="date">
               <span>Oct 12, 2019</span>
             </div>
             <a href="#">
               <h3>Journeys Are Best Measured In
                 New Friends</h3>
             </a>
           </div>
         </div>
       </div>
       <div class="col-lg-4 col-md-6">
         <div class="single_trip">
           <div class="thumb">
             <%= image_tag("trip/3.png", :alt=>"") %>
           </div>
           <div class="info">
             <div class="date">
               <span>Oct 12, 2019</span>
             </div>
             <a href="#">
               <h3>Journeys Are Best Measured In
                 New Friends</h3>
             </a>
           </div>
         </div>
       </div>
     </div>
   </div>
 </div>

app/views/shared/_videos.html.erb
<div class="video_area video_bg overlay">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="video_wrap text-center">
          <h3>Enjoy Video</h3>
          <div class="video_icon">
            <a class="popup-video video_play_button" href="https://www.youtube.com/watch?v=f59dDEk57i0">
              <i class="fa fa-play"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>