config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  resources :users
  get "/register", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  namespace :admin do
    get "/", to: "application#home"
    resources :users, :tours
  end

  resources :categorys, only: %i(index show) do
    resources :tours, only: %i(index show)  do
      resources :tour_details, only: %i(index show)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  enum permission: {trainee: 0, supervisor: 1}

  # Relationship
  has_many :blogs, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :books, dependent: :destroy
  # Call Back
  before_save :email_downcase

  # Validate Name
  validates :name, presence: true,
             length: {minimum: Settings.user.name.min_length,
                      maximum: Settings.user.name.max_length}

  # Validate Email
  VALIDATES_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true,
            length: {maximum: Settings.user.email.max_length},
            format: {with: VALIDATES_EMAIL_REGEX}

  # Validate Password
  validates :password, presence: true,
            length: {minimum: Settings.user.password.min_length,
                     maximum: Settings.user.password.max_length},
            allow_nil: true
  has_secure_password

  # Validate Phone Number
  VALID_PHONE_NUMBER_REGEX = /\A\+?[0-9]+\z/.freeze
  validates :phone_number, length: {minimum: Settings.user.phone.min_length,
                                    maximum: Settings.user.phone.min_length},
                           format: {with: VALID_PHONE_NUMBER_REGEX}, allow_blank: true

  # Scope:
  scope :find_by_user_name, ->(name){where("username LIKE ?", "%#{name}%") if name.present?}

  def remember
    self.remember_token = User.new_token
    update remember_digest: User.digest(remember_token)
  end

  def forget
    update remember_digest: nil
  end

  def authenticated? attribute, remember_token
    digest = send "#{attribute}_digest"
    return false unless digest

    BCrypt::Password.new(digest).is_password?(remember_token)
  end
  class << self
    # return the hash digest of the given string
    def digest string
      cost = BCrypt::Engine::MIN_COST if ActiveModel::SecurePassword.min_cost
      cost = BCrypt::Engine.cost unless ActiveModel::SecurePassword.min_cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  private

  def email_downcase
    email.downcase!
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  include Admin::ApplicationHelper

  before_action :load_user, except: %i(index)

  def index
    @users = User.paginate page: params[:page]
  end

  def edit; end

  def update
    if @user.update user_params
      flash[:success] = "Information chaged"
      redirect_to @user
    else
      flash[:danger] = "Check Information User Please !"
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = "User Deleted"
    else
      flash[:danger] = "User don't exist !"
    end
    redirect_to admin_users_path
  end

  private
  def load_user
    @user = User.find_by id: params[:id]
    return if @user

    flash[:danger] = "User don't exits"
    redirect_to admin_user_path
  end

  def user_params
    params.require(:user).permit(:name, :address, :phone_number, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: %i(new create)
  before_action :load_user, except: %i(new create)
  before_action :check_user_edit, only: %i(edit update)
  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params_create
    @user.user_contact.new
    if @user.save
      flash[:sucess] = "Register Sucess ! "
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    if @user.update(user_params_edit)
      flash[:success] = "Information changed"
      redirect_to @user
    else
      flash[:danger] = "Check Information Please !"
      render :edit
    end
  end

  def edit; end

  private

  def user_params_create
    params.require(:user).permit(:name, :email,
                                 :password, :password_confirmation)
  end

  def user_params_edit
    params.require(:user).permit(:name,:address,:phone_number,
                                 :password, :password_confirmation)
  end

  def load_user
    @user = User.find_by id: params[:id]
    return if @user

    flash[:danger] = "User don't correct"
    redirect_to root_path
  end

  def check_user_edit
    return if current_user? @user

    redirect_to edit_user_path(@current_user)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<% provide :title, "Edit" %>
<% provide :button_text, "Save Change" %>
<div class="page-wrapper">
  <div class="page-content--bge5">
    <div class="container">
      <div class="login-wrap">
        <div class="login-content">
          <div class="login-logo">
            <a href="#">
              <%= image_tag("logo_register.png", :alt=>"") %> </a>
          </div>
          <%= render  "users/form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<% provide :title, "Manager User " %>
<div class="row">
  <div class="col-lg">
    <h2 class="title-1 m-b-25">User Manager</h2>
    <div class="table-responsive table--no-card m-b-40">
      <div class="just-item-center text-center">
        <%= will_paginate %>
      </div>
      <table class="table table-borderless table-striped table-earning">
        <thead>
          <tr>
            <th>User</th>
            <th>Email</th>
            <th>Address</th>
            <th class="text-right">Phone Number</th>
            <th class="text-right"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.address %></td>
            <td class="text-right"><%= user.phone_number %></td>
            <td>
              <div class="table-data-feature">
                <%= link_to  user do %>
                <button class="item" data-toggle="tooltip" data-placement="top" title="Details">
                  <i class="zmdi zmdi-assignment"></i>
                </button>
                <% end %>
                <%= link_to edit_admin_user_path(user) do %>
                <button class="item" data-toggle="tooltip" data-placement="top" title="Edit">
                  <i class="zmdi zmdi-edit"></i>
                </button>
                <% end %>
                <%= link_to admin_user_path(user), method: :delete, data: {confirm: " Are You Sure !" } do %>
                <button class="item" data-toggle="tooltip" data-placement="top" title="Delete">
                  <i class="zmdi zmdi-delete"></i>
                </button>
                <% end %>
              </div>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="just-item-center text-center">
        <%= will_paginate %>
      </div>
    </div>
  </div>
</div>